package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        // --------- UPDATE CODE -------------------------
        return users; // return null
        // -----------------------------------------------
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        // --------- UPDATE CODE -------------------------
        users.add(User.random()); // Id value must be modified when new User is generated
        // -----------------------------------------------
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        // --------- UPDATE CODE -------------------------
        int indice = 0;
        boolean found = false;
        while( indice < users.size() && !found){

            if(users.get(indice).equals(user)){
                users.remove(indice);
                found = true;
            }

            else indice = indice + 1;
        }
        // -----------------------------------------------
    }
}
